# Generated by Django 6.0.3 on 2026-04-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_workouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
