# Generated by Django 6.0.3 on 2026-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_workout_user_workout_client_workout_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/'),
        ),
    ]
