# Generated by Django 6.0.3 on 2026-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_workout_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
